### PR TITLE
Few modifications to include:

### PR DESCRIPTION
**Pull request by vlours**
- Support of multiple kubeconfig files from the find
- Usage of parameters to display usage and version
- Allow Custom MAX_DEPTH as parameter

### CODE REVIEW

**Comment by bostrt** [comment]
What do you think about dropping the `-p` flag in favor of accepting it as an argument. In other words, keeping behaviour like this:

```
# oc flogin ~/installs/
[0] ./installs/cluster41/auth/kubeconfig
[1] ./installs/cluster44/auth/kubeconfig
```

I say this since the only argument *should* be a path making the `-p` flag unnecessary.

**Comment by vlours** [comment]
Yes sure, that makes sense. 
Actually I introduce the -p because I also introduced a '-c' for the choice, and then I realized that the choice should be by default, and forgot to remove the '-p'.
Do you want me to do it, or would you like to do it after merging my PR? That's up to you, it's your repo :)

**Comment by bostrt** [comment]
If you have time to make the changes I would appreciate it. Otherwise, I can take a look Wednesday!

**Comment by vlours** [comment]
> What do you think about dropping the -p flag in favor of accepting it as an argument.

Done. 
Let me know how it's working for you.

**Pull request merged**
